name: DeepZF
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cudatoolkit=11
  - cudnn=8
  - python=3.6
  - pip
  - pip:
      - protein-bert
      - natsort
      - pandas
      - scikit-learn
      - keras==2.6.0
      - tensorflow==2.6.2
